
import React from 'react';

interface Props {
  spvDesign: any;
}

export const SpvTaxRegStep: React.FC<Props> = ({ spvDesign }) => {
  return (
    <div className="space-y-8 animate-fadeIn">
        
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 text-8xl opacity-5 grayscale">⚖️</div>
            <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2">
                <span className="w-2 h-2 bg-blue-500 rounded-full"></span> Regulatory Classification
            </h3>
            <div className="space-y-3">
                {spvDesign.regulatoryNotes.map((note: string, i: number) => (
                    <div key={i} className="flex gap-3 text-sm text-slate-300">
                        <span className="text-blue-500 font-bold">→</span>
                        {note}
                    </div>
                ))}
                {spvDesign.regulatoryNotes.length === 0 && <p className="text-slate-500 italic">Generating regulatory insights...</p>}
            </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 text-8xl opacity-5 grayscale">💰</div>
            <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2">
                <span className="w-2 h-2 bg-emerald-500 rounded-full"></span> Tax Implications
            </h3>
            <div className="space-y-3">
                {spvDesign.taxNotes.map((note: string, i: number) => (
                    <div key={i} className="flex gap-3 text-sm text-slate-300">
                        <span className="text-emerald-500 font-bold">→</span>
                        {note}
                    </div>
                ))}
                {spvDesign.taxNotes.length === 0 && <p className="text-slate-500 italic">Generating tax profile...</p>}
            </div>
        </div>

        <div className="p-4 bg-amber-900/20 border border-amber-500/30 rounded-xl flex gap-4 items-start">
            <span className="text-xl">⚠️</span>
            <p className="text-xs text-amber-200/80 leading-relaxed">
                <strong>Disclaimer:</strong> These notes are generated by AI based on the selected jurisdiction ({spvDesign.jurisdictionCode}) and legal form ({spvDesign.legalForm}). They do not constitute legal or tax advice. Please verify with a local counsel.
            </p>
        </div>

    </div>
  );
};
